name: build & Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Phase5-TDD

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Phase5-TDD

    - name: Upload result for job build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: .

    - name: Log info
      run: ls
      working-directory: ./Phase5-TDD

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Log info
      run: ls && ls InvertedIndex.Test/
      working-directory: ./Phase5-TDD

    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: ./Phase5-TDD

    - name: Publish code coverage reports to codecove.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./**/coverage.cobertura.xml
        fail_ci_if_error: true