name: publish

on:
  release:
    types:
      published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: Setup .NET 5

    - name: Get current release version
      id: version
      uses: pozetroninc/github-action-get-latest-release@main
      with:
        repository: Star-Academy/Summer1400-SE-Team24

    - name: Build library and generate NuGet Package
      run: dotnet pack -c Release -o artifacts -p:PackageVersion=${{ steps.version.outputs.release }}
      working-directory: ./Phase5-TDD/InvertedIndex

    - name: Publish NuGet Package
      run: dotnet nuget push ./**/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
